---
abstract: 'Convert sql into a client-side db with keyed access.'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-HTML-ClientDB
provides:
  DBIx::HTML::ClientDB:
    file: lib/DBIx/HTML/ClientDB.pm
    version: 1.08
requires:
  Carp: 0
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
version: 1.08
